include:
  - project: muni-kypo-images/ci-cd-virtual-images
    file: qemu.yml
  - project: muni-kypo-images/ci-cd-virtual-images
    file: vbox.yml

variables:
  NAME: "kali"
  TYPE: "linux"
  DISTRO: "debian"
  GUI_ACCESS: "true"
