include:
  - project: muni-kypo-images/ci-cd-virtual-images
    file: qemu.yml
  - project: muni-kypo-images/ci-cd-virtual-images
    file: vbox.yml

variables:
  NAME: "kali"
  TYPE: "linux"
  DISTRO: "debian"
  GUI_ACCESS: "true"

.build:
  before_script:
    - packer plugins install github.com/hashicorp/qemu
    - packer plugins install github.com/hashicorp/virtualbox
    - packer plugins install github.com/hashicorp/vagrant
