name: CI
on:
  workflow_call:
    secrets:
      OS_APPLICATION_CREDENTIAL_ID:
        required: true
      OS_APPLICATION_CREDENTIAL_SECRET:
        required: true
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "images"]
    container:
      image: ghcr.io/cyberrangecz/docker-image-builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged
      ports: [5900]
    steps:
      - uses: actions/checkout@v4
      - name: Install packer qemu plugin
        run: packer plugins install github.com/hashicorp/qemu
      - name: Build image
        run: packer build -only=qemu kali.json
      - name: Get short SHA
        uses: benjlevesque/short-sha@v3.0
      - name: Upload image
        run: >
          openstack image create --file target-qemu/* --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi
          --property hw_rng_model=virtio --property hw_qemu_guest_agent=yes --property os_require_quiesce=yes
          --property os_type=linux --property os_distro=debian --property owner_specified.openstack.version=$SHA
          --property owner_specified.openstack.gui_access=true --property owner_specified.openstack.custom=true --public kali-$SHA
        env:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.IMAGES_OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.IMAGES_OS_APPLICATION_CREDENTIAL_SECRET }}
          OS_AUTH_TYPE: v3applicationcredential
          OS_AUTH_URL: https://192.168.53.10:5000
          OS_IDENTITY_API_VERSION: 3
          OS_INTERFACE: public
          OS_REGION_NAME: RegionOne
          OS_INSECURE: true
